version: '3.4'

# Define services
#
services:
  web:
    image: nginx:1.15
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/project/
    depends_on:
      - fpm

  fpm:
    image: omeglast/weather-exporter:latest
    environment:
      DB_DRIVER: pgsql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
    depends_on:
      - postgres
