version: '3.4'

# Define services
#
services:
  web:
    image: nginx:1.15
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/project/
    depends_on:
      - fpm
    ports:
      - "81:80"

  fpm:
#    image: php:7-fpm-alpine
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - ./:/var/www/project/
    working_dir: /var/www/project/
    env_file:
      - .env
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: weather
      MYSQL_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: weather
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - web
