version: '3.4'

# Define services
#
services:
  fpm:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
#    volumes:
#      - ./:/var/www/
    env_file:
      - .env
    environment:
      DB_DRIVER: pgsql
      DB_USER: user
      DB_PASSWORD: passwd
      DB_DATABASE: weather
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "81:8080"

  cli:
    build:
      context: .
      dockerfile: docker/cli/Dockerfile
    #    volumes:
    #      - ./:/var/www/
    env_file:
      - .env
    environment:
      DB_DRIVER: pgsql
      DB_USER: user
      DB_PASSWORD: passwd
      DB_DATABASE: weather
      DB_HOST: postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

#  prometheus:
#    image: prom/prometheus
#    volumes:
#      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - '9090:9090'
#    depends_on:
#      - web
