version: '3.4'

# Define services
#
services:
  web:
    image: php:7-cli-alpine
    volumes:
      - ./:/var/www/project
    working_dir: /var/www/project
    env_file:
      - .env
    ports:
      - "81:80"
    command: php -S web:80 -t public/

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - web
