version: '3.4'

# Define services
#
services:
  web:
    image: nginx:1.15
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/project/
    depends_on:
      - fpm
    ports:
      - '81:80'

  fpm:
    image: php:7-fpm-alpine
    volumes:
      - ./:/var/www/project/
    working_dir: /var/www/project/

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - web
